/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sagnik Chakraborty
 */
public class AccountCreation_2 extends javax.swing.JFrame {

    /**
     * Creates new form AccountCreation_2
     */
    
    String formNo = "", form = "";
    
    public AccountCreation_2(String frmno) {
        initComponents();
        
        formNo = frmno;
        
        setVisible(true);
        setResizable(false);
        form = "Form No.: "+formNo;
        jL1.setText(form);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        AddressType = new javax.swing.ButtonGroup();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jRB1 = new javax.swing.JRadioButton();
        jRB2 = new javax.swing.JRadioButton();
        jRB3 = new javax.swing.JRadioButton();
        jRB4 = new javax.swing.JRadioButton();
        jRB5 = new javax.swing.JRadioButton();
        jL5 = new javax.swing.JLabel();
        jL6 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jL7 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        jL8 = new javax.swing.JLabel();
        jTF5 = new javax.swing.JTextField();
        jL9 = new javax.swing.JLabel();
        jTF6 = new javax.swing.JTextField();
        jL10 = new javax.swing.JLabel();
        jTF7 = new javax.swing.JTextField();
        jB1 = new javax.swing.JButton();
        jL11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jL2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jL2.setText("Page 2/3");

        jL3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jL3.setText("Address Details:-");

        jL4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL4.setText("ADDRESS TYPE*:");

        AddressType.add(jRB1);
        jRB1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB1.setText("Residential / Business");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB1, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB1, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        AddressType.add(jRB2);
        jRB2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB2.setText("Residential");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB2, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB2, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        AddressType.add(jRB3);
        jRB3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB3.setText("Business");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB3, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB3, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        AddressType.add(jRB4);
        jRB4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB4.setText("Registered Office");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB4, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB4, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        AddressType.add(jRB5);
        jRB5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB5.setText("Unspecified");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB5, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB5, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL5.setText("ADDRESS*:");

        jL6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL6.setText("CITY/VILLAGE*:");

        jTF3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL7.setText("DISTRICT:");

        jTF4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL8.setText("STATE*:");

        jTF5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL9.setText("PIN*:");

        jTF6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL10.setText("COUNTRY NAME*:");

        jTF7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jB1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB1.setText("NEXT");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jL11.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL11.setText("ACCOUNT CREATION");

        jTA1.setColumns(20);
        jTA1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTA1.setRows(5);
        jScrollPane1.setViewportView(jTA1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jL3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jL6)
                                            .addComponent(jL5)
                                            .addComponent(jL8)
                                            .addComponent(jL10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jL9))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jL7)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jL4)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB3)))))))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(jL11)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jL3)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRB1)
                        .addComponent(jRB2)
                        .addComponent(jRB3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB4)
                    .addComponent(jRB5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jL5)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL6)
                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL7)
                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL8)
                        .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL9)
                        .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL10)
                    .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB1)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jL11)
                    .addContainerGap(525, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String addType = "";
            
            addType = AddressType.getSelection().getActionCommand();
            
            //String query = " insert into AccountInfo (AddType, Address, City, District, State, PinCode, Country)" + " values (?, ?, ?, ?, ?, ?, ?)";
            String query = "update AccountInfo set AddType=?, Address=?, City=?, District=?, State=?, PinCode=?, Country=? where FormNo = ?";
            
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,addType);
            jRB1.setEnabled(false);
            jRB2.setEnabled(false);
            jRB3.setEnabled(false);
            jRB4.setEnabled(false);
            jRB5.setEnabled(false);
            preparedStmt.setString(2,jTA1.getText());
            jTA1.setEditable(false);
            preparedStmt.setString(3,jTF3.getText());
            jTF3.setEditable(false);
            preparedStmt.setString(4,jTF4.getText());
            jTF4.setEditable(false);
            preparedStmt.setString(5,jTF5.getText());
            jTF5.setEditable(false);
            preparedStmt.setString(6,jTF6.getText());
            jTF6.setEditable(false);
            preparedStmt.setString(7,jTF7.getText());
            jTF7.setEditable(false);
            preparedStmt.setString(8,formNo);
            
            preparedStmt.execute();
            
            //JOptionPane.showMessageDialog(null, "Insertion was Successfull!!");
            
            new AccountCreation_3(formNo);
            dispose();
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_jB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountCreation_2("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AddressType;
    private javax.swing.JButton jB1;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JRadioButton jRB1;
    private javax.swing.JRadioButton jRB2;
    private javax.swing.JRadioButton jRB3;
    private javax.swing.JRadioButton jRB4;
    private javax.swing.JRadioButton jRB5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA1;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JTextField jTF6;
    private javax.swing.JTextField jTF7;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
