/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sagnik Chakraborty
 */
public class AccountInfo extends javax.swing.JFrame {

    /**
     * Creates new form AccountInfo
     */
    
    String name = "";
    String AccNo = "";
    String ToggleAcc = "";
    String bnName = "";
    String formNo = "";
    
    public AccountInfo(String nm, String acc, String bnm, String frmn) {
        initComponents();
        
        name = nm;
        AccNo = acc;
        bnName = bnm;
        formNo = frmn;
        
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, AccNo);
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                jTF6.setText(name);
                String acno = "000000-XXXXXX"+AccNo.substring(6);
                jTF3.setText(acno);
                ToggleAcc = acno;
                String cdno = rs.getString(4);
                String card = "XXXX XXXX XXXX "+cdno.substring(12);
                jTF9.setText(card);
                jTF5.setText(rs.getString(3));
                jTF1.setText(rs.getString(2));
                jTF2.setText("*****");
                jTF4.setText(rs.getString(1));
                jTF7.setText(rs.getString(8));
                jTF8.setText(rs.getString(9));
                jTF10.setText("XXXX");
                jTF11.setText(rs.getString(10));
                jTF12.setText(rs.getString(11));
                jTF13.setText(rs.getString(12));
                jTF14.setText(rs.getString(13));
                jTF15.setText(rs.getString(14));
                jTF16.setText(rs.getString(15));
                if(rs.getString(15) == "")
                    jTF16.setText("-");
                //else
                    //jTF16.setText(rs.getString(15));
                jTF17.setText(rs.getString(16));
                jTF18.setText(rs.getString(17));
                jTA1.setText(rs.getString(18));
                jTF19.setText(rs.getString(19));
                jTF20.setText(rs.getString(20));
                jTF21.setText(rs.getString(22));
                jTF22.setText(rs.getString(21));
                jTF23.setText(rs.getString(23));
                jTF24.setText(rs.getString(24));
                jTF25.setText(rs.getString(25));
                jTF26.setText(rs.getString(26));
                jTF27.setText(rs.getString(27));
                jTF28.setText(rs.getString(28));
            }
            
            String balance = "BalanceInfo_"+AccNo;
            
            query = "select * from "+balance+" order by date_d_w asc";
            
            preparedStmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE , ResultSet.CONCUR_UPDATABLE);
            
            rs = preparedStmt.executeQuery();
            
            if(rs.last() == true) 
            {  
                jTF29.setText(rs.getString(5)+".00");
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
        
        setVisible(true);
        //setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jL29 = new javax.swing.JLabel();
        jL30 = new javax.swing.JLabel();
        jL31 = new javax.swing.JLabel();
        jL32 = new javax.swing.JLabel();
        jL33 = new javax.swing.JLabel();
        jL34 = new javax.swing.JLabel();
        jL35 = new javax.swing.JLabel();
        jL36 = new javax.swing.JLabel();
        jL37 = new javax.swing.JLabel();
        jL38 = new javax.swing.JLabel();
        jL39 = new javax.swing.JLabel();
        jL40 = new javax.swing.JLabel();
        jL41 = new javax.swing.JLabel();
        jL42 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jL43 = new javax.swing.JLabel();
        jL44 = new javax.swing.JLabel();
        jL45 = new javax.swing.JLabel();
        jL46 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jL47 = new javax.swing.JLabel();
        jL48 = new javax.swing.JLabel();
        jL49 = new javax.swing.JLabel();
        jL50 = new javax.swing.JLabel();
        jL51 = new javax.swing.JLabel();
        jL52 = new javax.swing.JLabel();
        jL53 = new javax.swing.JLabel();
        jL54 = new javax.swing.JLabel();
        jL55 = new javax.swing.JLabel();
        jL56 = new javax.swing.JLabel();
        jL57 = new javax.swing.JLabel();
        jL58 = new javax.swing.JLabel();
        jL59 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jTF1 = new javax.swing.JTextField();
        jTF2 = new javax.swing.JTextField();
        jTF3 = new javax.swing.JTextField();
        jTF4 = new javax.swing.JTextField();
        jTF5 = new javax.swing.JTextField();
        jTF6 = new javax.swing.JTextField();
        jTF7 = new javax.swing.JTextField();
        jTF8 = new javax.swing.JTextField();
        jTF9 = new javax.swing.JTextField();
        jTF10 = new javax.swing.JTextField();
        jTF11 = new javax.swing.JTextField();
        jTF12 = new javax.swing.JTextField();
        jTF13 = new javax.swing.JTextField();
        jTF14 = new javax.swing.JTextField();
        jTF15 = new javax.swing.JTextField();
        jTF16 = new javax.swing.JTextField();
        jTF17 = new javax.swing.JTextField();
        jTF18 = new javax.swing.JTextField();
        jTF19 = new javax.swing.JTextField();
        jTF20 = new javax.swing.JTextField();
        jTF21 = new javax.swing.JTextField();
        jTF22 = new javax.swing.JTextField();
        jTF23 = new javax.swing.JTextField();
        jTF24 = new javax.swing.JTextField();
        jL61 = new javax.swing.JLabel();
        jTF25 = new javax.swing.JTextField();
        jTF26 = new javax.swing.JTextField();
        jTF27 = new javax.swing.JTextField();
        jTF28 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA1 = new javax.swing.JTextArea();
        jL62 = new javax.swing.JLabel();
        jL63 = new javax.swing.JLabel();
        jTF29 = new javax.swing.JTextField();
        jTB1 = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jL29.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL29.setText("SYNDICATE BANK");

        jL30.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jL30.setText("Account Information:-");

        jL31.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL31.setText("1. FORM NO.:");

        jL32.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL32.setText("2. BRANCH NAME:");

        jL33.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL33.setText("CUSTOMER ID:");

        jL34.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL34.setText("PASSWORD:");

        jL35.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL35.setText("3. NAME:");

        jL36.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL36.setText("4. EMAIL:");

        jL37.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL37.setText("5. MOBILE NO.:");

        jL38.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL38.setText("6. CARD NO.:");

        jL39.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL39.setText("7. ATM PIN:");

        jL40.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL40.setText("8. D.O.B:");

        jL41.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL41.setText("9. GENDER:");

        jL42.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL42.setText("10. MARITAL STATUS:");

        jL43.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL43.setText("11. AADHAAR NO.:");

        jL44.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL44.setText("12. FATHER NAME:");

        jL45.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL45.setText("13. SPOUSE NAME:");

        jL46.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL46.setText("14. MOTHER NAME:");

        jL47.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL47.setText("15. ADDRESS TYPE:");

        jL48.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL48.setText("16. ADDRESS:");

        jL49.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL49.setText("17. CITY:");

        jL50.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL50.setText("18. DISTRICT:");

        jL51.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL51.setText("19. STATE:");

        jL52.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL52.setText("20. PINCODE:");

        jL53.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL53.setText("21. COUNTRY:");

        jL54.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL54.setText("22. MONTHLY INCOME:");

        jL55.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL55.setText("23. RELIGION:");

        jL56.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL56.setText("24. CATEGORY:");

        jL57.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL57.setText("25. EDUCATIONAL QUALIFICATION:");

        jL58.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL58.setText("26. IDENTITY PROOF:");

        jL59.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL59.setText("ACCOUNT NO.:");

        jB1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jB1.setText("SAVE");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jB2.setText("BACK");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jTF1.setEditable(false);
        jTF1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF2.setEditable(false);
        jTF2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF3.setEditable(false);
        jTF3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF4.setEditable(false);
        jTF4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF5.setEditable(false);
        jTF5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF6.setEditable(false);
        jTF6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF7.setEditable(false);
        jTF7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF8.setEditable(false);
        jTF8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF9.setEditable(false);
        jTF9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF10.setEditable(false);
        jTF10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF11.setEditable(false);
        jTF11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF12.setEditable(false);
        jTF12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF13.setEditable(false);
        jTF13.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF14.setEditable(false);
        jTF14.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF15.setEditable(false);
        jTF15.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF16.setEditable(false);
        jTF16.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF17.setEditable(false);
        jTF17.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF18.setEditable(false);
        jTF18.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF19.setEditable(false);
        jTF19.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF20.setEditable(false);
        jTF20.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF21.setEditable(false);
        jTF21.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF22.setEditable(false);
        jTF22.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF23.setEditable(false);
        jTF23.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF24.setEditable(false);
        jTF24.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL61.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL61.setText("Rs.");

        jTF25.setEditable(false);
        jTF25.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF26.setEditable(false);
        jTF26.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF27.setEditable(false);
        jTF27.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF28.setEditable(false);
        jTF28.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTA1.setEditable(false);
        jTA1.setColumns(20);
        jTA1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTA1.setRows(5);
        jScrollPane1.setViewportView(jTA1);

        jL62.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL62.setText("BALANCE:");

        jL63.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL63.setText("Rs.");

        jTF29.setEditable(false);
        jTF29.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTB1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jTB1.setText("UNHIDE");
        jTB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jL29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL63)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF29, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB2)
                        .addGap(18, 18, 18)
                        .addComponent(jB1)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jL48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)
                                .addGap(254, 254, 254))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF25, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL56)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF26, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL51)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF22, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL52)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF21, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF14, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF13, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF15, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF16, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF17, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF18, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL53)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF23, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL57)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF27, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL58)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF28, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jL61)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF24, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL49)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF19, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL50)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF20, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jL36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jL30)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL35)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF6))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL40)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF11, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL41)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF12, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL38)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF9))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL39)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF10, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL32)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL34)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTB1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jL33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jL59)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 70, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL29)
                .addGap(18, 18, 18)
                .addComponent(jL30)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL33)
                    .addComponent(jL59)
                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTB1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL34)
                        .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL62)
                    .addComponent(jL63)
                    .addComponent(jTF29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL31)
                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL32)
                    .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL35)
                    .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL36)
                    .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL37)
                    .addComponent(jTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL38)
                    .addComponent(jTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL39)
                    .addComponent(jTF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL40)
                    .addComponent(jTF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL41)
                    .addComponent(jTF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL42)
                    .addComponent(jTF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL43)
                    .addComponent(jTF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL44)
                    .addComponent(jTF15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jL45))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL46)
                    .addComponent(jTF17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL47)
                    .addComponent(jTF18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL48)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL49)
                    .addComponent(jL50)
                    .addComponent(jTF19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL51)
                    .addComponent(jL52)
                    .addComponent(jTF21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL53)
                    .addComponent(jTF23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL54)
                    .addComponent(jL61)
                    .addComponent(jTF24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL55)
                    .addComponent(jTF25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL56)
                    .addComponent(jTF26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL57)
                    .addComponent(jTF27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL58)
                    .addComponent(jTF28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1)
                    .addComponent(jB2))
                .addContainerGap(682, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        new ProfileNet(name,AccNo,bnName,formNo);
        dispose();
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        //D:\Banking_documents\AccountInfo
        try
        {
            java.time.LocalDate ldate = java.time.LocalDate.now();
            java.time.LocalTime ltime = java.time.LocalTime.now();
            String date = ldate.toString() +"_"+ltime.toString().substring(0, 2)+"_"+ltime.toString().substring(3, 5)+"_"+ltime.toString().substring(6);
            //String fileName = "D:\\Banking_documents\\MiniStatements\\MiniStatement_"+date+".txt";
            //Path path = Paths.get(fileName);
            //Path p= Files.createFile(path);
            //FileOutputStream fos=new FileOutputStream(fileName, true);
            
            String path = "D:\\Banking_documents\\AccountInfo";
            
            File theDir = new File(path);
            
            if (!theDir.exists())
            {
                theDir.mkdirs();
            }
            
            String fn = path+"\\AccountInfo_"+date+".pdf";
            
            Document document = new Document();
            
            PdfWriter.getInstance(document, new FileOutputStream(fn));
            
            //document.open();
            
            //Paragraph para = new Paragraph();
            
            //document.close();
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, AccNo);
            
            String cdno = "", card = "", brnch = "", Bal = "";
            String CustID = "", pwd = "", formNo = "", email = "", mobNo = "", ATM = "";
            String dob = "", gender = "", marStat = "", aadhNo = "", fathnm = "", sponm = "";
            String mothnm = "", addtyp = "", address = "", city = "", district = "", pin = "", state = "", country = "";
            String monthInc = "", rel = "", cat = "", edqu = "", idProf = "";
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                //jL10.setText(name);
                //acno = "000000-XXXXXX"+AccNo.substring(6);
                //jL11.setText(acno);
                cdno = rs.getString(4);
                card = "XXXX XXXX XXXX "+cdno.substring(12);
                //jL12.setText(card);
                brnch = rs.getString(3);
                
                CustID = rs.getString(2);
                pwd = "*****";
                formNo = rs.getString(1);
                email = rs.getString(8);
                mobNo = rs.getString(9);
                ATM = "XXXX";
                dob = rs.getString(10);
                gender = rs.getString(11);
                marStat = rs.getString(12);
                aadhNo = rs.getString(13);
                fathnm = rs.getString(14);
                sponm = rs.getString(15);
                if(sponm == "")
                    sponm = "-";
                mothnm = rs.getString(16);
                addtyp = rs.getString(17);
                address = rs.getString(18);
                city = rs.getString(19);
                district = rs.getString(20);
                pin = rs.getString(22);
                state = rs.getString(21);
                country = rs.getString(23);
                monthInc = rs.getString(24);
                rel = rs.getString(25);
                cat = rs.getString(26);
                edqu = rs.getString(27);
                idProf = rs.getString(28);
            }
            
            String balance = "BalanceInfo_"+AccNo;
            
            query = "select * from "+balance+" order by date_d_w asc";
            
            preparedStmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE , ResultSet.CONCUR_UPDATABLE);
            
            rs = preparedStmt.executeQuery();
            
            if(rs.last() == true) 
            {  
                Bal = rs.getString(5)+".00";
            }
            
            String str = "";
            
            str = "\t\tSYNDICATE BANK\n\n"+"ACCOUNT INFORMATION:-\n\n";
            str += "CUSTOMER ID:  "+CustID+"                ACCOUNT NUMBER:  "+ToggleAcc+"\nPASSWORD:  "+pwd+"\n\nBALANCE:  Rs. "+Bal;
            str += "\n\nFORM NO.:  "+formNo+"\nBRANCH NAME:  "+brnch+"\nNAME:  "+name+"\nEMAIL:  "+email+"\nMOBILE NO.:  +91 "+mobNo+"\nCARD NO.:  "+card;
            str += "\nATM PIN:  "+ATM+"\nD.O.B:  "+dob+"\nGENDER:  "+gender+"\n\n------------------------------------------------\n";
            str += "\nMARITAL STATUS:  "+marStat+"\nAADHAAR NO.:  "+aadhNo+"\nFATHER NAME:  "+fathnm+"\nSPOUSE NAME:  "+sponm+"\nMOTHER NAME:  "+mothnm;
            str += "\n\n------------------------------------------------\n"+"\nADDRESS TYPE:  "+addtyp+"\nADDRESS:  "+address+"\nCITY:  "+city;
            str += "                DISTRICT:  "+district+"\nSTATE:  "+state+"                PINCODE:  "+pin+"\nCOUNTRY:  "+country+"\n\n------------------------------------------------\n";
            str += "\nMONTHLY INCOME:  Rs. "+monthInc+"\nRELIGION:  "+rel+"                CATEGORY:  "+cat+"\nEDUCATIONAL QUALIFICATION:  "+edqu+"\nIDENTITY PROOF:  "+idProf;
            str += "\n\n------------------------------------------------";
            
            document.open();
            
            Paragraph para = new Paragraph(str);
            
            document.add(para);
            
            document.close();
            
            JOptionPane.showMessageDialog(null, "Account Information Successfully Saved!!");
        }
        catch(Exception e)  
        {  
            e.printStackTrace();          
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jTB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTB1ActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, AccNo);
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                
                String acno = "000000-XXXXXX"+AccNo.substring(6);
                if(jTB1.isSelected())
                {
                    jTF3.setText("000000-"+AccNo);
                    jTB1.setText("HIDE");
                    ToggleAcc = "000000-"+AccNo;
                }
                else
                {
                    jTF3.setText(acno);
                    jTB1.setText("UNHIDE");
                    ToggleAcc = acno;
                }
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_jTB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountInfo("","","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JLabel jL29;
    private javax.swing.JLabel jL30;
    private javax.swing.JLabel jL31;
    private javax.swing.JLabel jL32;
    private javax.swing.JLabel jL33;
    private javax.swing.JLabel jL34;
    private javax.swing.JLabel jL35;
    private javax.swing.JLabel jL36;
    private javax.swing.JLabel jL37;
    private javax.swing.JLabel jL38;
    private javax.swing.JLabel jL39;
    private javax.swing.JLabel jL40;
    private javax.swing.JLabel jL41;
    private javax.swing.JLabel jL42;
    private javax.swing.JLabel jL43;
    private javax.swing.JLabel jL44;
    private javax.swing.JLabel jL45;
    private javax.swing.JLabel jL46;
    private javax.swing.JLabel jL47;
    private javax.swing.JLabel jL48;
    private javax.swing.JLabel jL49;
    private javax.swing.JLabel jL50;
    private javax.swing.JLabel jL51;
    private javax.swing.JLabel jL52;
    private javax.swing.JLabel jL53;
    private javax.swing.JLabel jL54;
    private javax.swing.JLabel jL55;
    private javax.swing.JLabel jL56;
    private javax.swing.JLabel jL57;
    private javax.swing.JLabel jL58;
    private javax.swing.JLabel jL59;
    private javax.swing.JLabel jL61;
    private javax.swing.JLabel jL62;
    private javax.swing.JLabel jL63;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTA1;
    private javax.swing.JToggleButton jTB1;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF10;
    private javax.swing.JTextField jTF11;
    private javax.swing.JTextField jTF12;
    private javax.swing.JTextField jTF13;
    private javax.swing.JTextField jTF14;
    private javax.swing.JTextField jTF15;
    private javax.swing.JTextField jTF16;
    private javax.swing.JTextField jTF17;
    private javax.swing.JTextField jTF18;
    private javax.swing.JTextField jTF19;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF20;
    private javax.swing.JTextField jTF21;
    private javax.swing.JTextField jTF22;
    private javax.swing.JTextField jTF23;
    private javax.swing.JTextField jTF24;
    private javax.swing.JTextField jTF25;
    private javax.swing.JTextField jTF26;
    private javax.swing.JTextField jTF27;
    private javax.swing.JTextField jTF28;
    private javax.swing.JTextField jTF29;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JTextField jTF6;
    private javax.swing.JTextField jTF7;
    private javax.swing.JTextField jTF8;
    private javax.swing.JTextField jTF9;
    // End of variables declaration//GEN-END:variables
}
