/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sagnik Chakraborty
 */
public class AccountCreation_1 extends javax.swing.JFrame {

    /**
     * Creates new form accountCreation
     */
    
    String formNo = "", form = "", bnName = "";
    int flag = 0;
    
    public AccountCreation_1(String frmno, String bnnm) {
        initComponents();
        
        formNo = frmno;
        bnName = bnnm;
        
        setVisible(true);
        setResizable(false);
        form = "Form No.: "+formNo;
        jL1.setText(form);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        GenderGroup = new javax.swing.ButtonGroup();
        MaritalGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jL5 = new javax.swing.JLabel();
        jTF2 = new javax.swing.JTextField();
        jL6 = new javax.swing.JLabel();
        jL7 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox();
        jL8 = new javax.swing.JLabel();
        jCB2 = new javax.swing.JComboBox();
        jL9 = new javax.swing.JLabel();
        jCB3 = new javax.swing.JComboBox();
        jL10 = new javax.swing.JLabel();
        jRB1 = new javax.swing.JRadioButton();
        jRB2 = new javax.swing.JRadioButton();
        jRB3 = new javax.swing.JRadioButton();
        jL11 = new javax.swing.JLabel();
        jRB4 = new javax.swing.JRadioButton();
        jRB5 = new javax.swing.JRadioButton();
        jRB6 = new javax.swing.JRadioButton();
        jTF3 = new javax.swing.JTextField();
        jL12 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        jL13 = new javax.swing.JLabel();
        jL14 = new javax.swing.JLabel();
        jTF5 = new javax.swing.JTextField();
        jL15 = new javax.swing.JLabel();
        jL16 = new javax.swing.JLabel();
        jTF6 = new javax.swing.JTextField();
        jTF7 = new javax.swing.JTextField();
        jB1 = new javax.swing.JButton();
        jL17 = new javax.swing.JLabel();
        jTF8 = new javax.swing.JTextField();
        jL18 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jL2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jL2.setText("Page 1/3");

        jL3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jL3.setText("Personal Details:-");

        jL4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL4.setText("NAME*:");

        jTF1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL5.setText("MOBILE NO.:");

        jTF2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF2ActionPerformed(evt);
            }
        });

        jL6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL6.setText("D.O.B*:");

        jL7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL7.setText("DD:");

        jCB1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB1ActionPerformed(evt);
            }
        });

        jL8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL8.setText("MM:");

        jCB2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));

        jL9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL9.setText("YYYY:");

        jCB3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jL10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL10.setText("GENDER*:");

        GenderGroup.add(jRB1);
        jRB1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB1.setText("MALE");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB1, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB1, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        GenderGroup.add(jRB2);
        jRB2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB2.setText("FEMALE");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB2, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB2, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        GenderGroup.add(jRB3);
        jRB3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB3.setText("OTHERS");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB3, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB3, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jL11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL11.setText("MARITAL STATUS*:");

        MaritalGroup.add(jRB4);
        jRB4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB4.setText("MARRIED");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB4, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB4, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB4MouseClicked(evt);
            }
        });
        jRB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB4ActionPerformed(evt);
            }
        });

        MaritalGroup.add(jRB5);
        jRB5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB5.setText("UN-MARRIED");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB5, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB5, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB5MouseClicked(evt);
            }
        });

        MaritalGroup.add(jRB6);
        jRB6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB6.setText("OTHERS:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB6, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB6, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB6MouseClicked(evt);
            }
        });

        jTF3.setEditable(false);
        jTF3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL12.setText("AADHAAR NUMBER*:");

        jTF4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jL13.setText("+91");

        jL14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL14.setText("NAME of FATHER*:");

        jTF5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL15.setText("NAME of SPOUSE:");

        jL16.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL16.setText("NAME of MOTHER*:");

        jTF6.setEditable(false);
        jTF6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jTF7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jB1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB1.setText("NEXT");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jL17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL17.setText("EMAIL:");

        jTF8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL18.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL18.setText("Account Creation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jL15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jL14)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jL2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jL4)
                                        .addComponent(jL6)
                                        .addComponent(jL10)
                                        .addComponent(jL11)
                                        .addComponent(jL12)
                                        .addComponent(jL17)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jL5)
                                            .addGap(29, 29, 29)
                                            .addComponent(jL13)))
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRB1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRB2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRB3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTF1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jL7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jL8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jL9)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTF8, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTF4, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jRB4)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jRB5)))
                                            .addGap(18, 18, 18)
                                            .addComponent(jRB6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(jL18)
                    .addContainerGap(228, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jL1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jL2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL3)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL4)
                            .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jL17))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL5)
                    .addComponent(jL13)
                    .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL7)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL8)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL9)
                    .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL6))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL10)
                    .addComponent(jRB1)
                    .addComponent(jRB2)
                    .addComponent(jRB3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL11)
                    .addComponent(jRB4)
                    .addComponent(jRB5)
                    .addComponent(jRB6)
                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL12)
                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL14)
                    .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL16))
                .addGap(18, 18, 18)
                .addComponent(jB1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jL18)
                    .addContainerGap(626, Short.MAX_VALUE)))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB1ActionPerformed
        
    }//GEN-LAST:event_jCB1ActionPerformed

    private void jTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF2ActionPerformed

    private void jRB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB4MouseClicked
        jTF6.setEditable(true);
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB4MouseClicked

    private void jRB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB4ActionPerformed
        //jTF6.setEditable(true);
        //jTF3.setEditable(false);
    }//GEN-LAST:event_jRB4ActionPerformed

    private void jRB5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB5MouseClicked
        jTF6.setEditable(false);
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB5MouseClicked

    private void jRB6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB6MouseClicked
        jTF6.setEditable(false);
        jTF3.setEditable(true);
        flag = 1;
    }//GEN-LAST:event_jRB6MouseClicked

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String dob = "";
            String gender = "";
            String marStatus = "";
            
            dob = jCB1.getSelectedItem().toString() + "/" + jCB2.getSelectedItem().toString() + "/" + jCB3.getSelectedItem().toString();
            
            gender = GenderGroup.getSelection().getActionCommand();
            
            if(flag == 1)
                marStatus = jTF3.getText();
            else
                marStatus = MaritalGroup.getSelection().getActionCommand();
            
            String query = " insert into AccountInfo (Name, Email, MobNo, Dob, Gender, MarStat, AadhNo, FathName, SpoName, MothName, FormNo, BranchName)" + " values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,jTF1.getText());
            jTF1.setEditable(false);
            preparedStmt.setString(2,jTF8.getText());
            jTF8.setEditable(false);
            preparedStmt.setString(3,"+91 " + jTF2.getText());
            jTF2.setEditable(false);
            preparedStmt.setString(4,dob);
            jCB1.setEnabled(false);
            jCB2.setEnabled(false);
            jCB3.setEnabled(false);
            preparedStmt.setString(5,gender);
            jRB1.setEnabled(false);
            jRB2.setEnabled(false);
            jRB3.setEnabled(false);
            preparedStmt.setString(6,marStatus);
            jRB4.setEnabled(false);
            jRB5.setEnabled(false);
            jRB6.setEnabled(false);
            jTF3.setEditable(false);
            preparedStmt.setString(7,jTF4.getText());
            jTF4.setEditable(false);
            preparedStmt.setString(8,jTF5.getText());
            jTF5.setEditable(false);
            preparedStmt.setString(9,jTF6.getText());
            jTF6.setEditable(false);
            preparedStmt.setString(10,jTF7.getText());
            jTF7.setEditable(false);
            preparedStmt.setString(11,formNo);
            preparedStmt.setString(12,bnName);
            
            preparedStmt.execute();
            
            //JOptionPane.showMessageDialog(null, "Insertion was Successfull!!");
            
            new AccountCreation_2(formNo);
            dispose();
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
        
        //System.out.println(GenderGroup.getSelection().getActionCommand());
    }//GEN-LAST:event_jB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountCreation_1("","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.ButtonGroup MaritalGroup;
    private javax.swing.JButton jB1;
    private javax.swing.JComboBox jCB1;
    private javax.swing.JComboBox jCB2;
    private javax.swing.JComboBox jCB3;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL12;
    private javax.swing.JLabel jL13;
    private javax.swing.JLabel jL14;
    private javax.swing.JLabel jL15;
    private javax.swing.JLabel jL16;
    private javax.swing.JLabel jL17;
    private javax.swing.JLabel jL18;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRB1;
    private javax.swing.JRadioButton jRB2;
    private javax.swing.JRadioButton jRB3;
    private javax.swing.JRadioButton jRB4;
    private javax.swing.JRadioButton jRB5;
    private javax.swing.JRadioButton jRB6;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JTextField jTF6;
    private javax.swing.JTextField jTF7;
    private javax.swing.JTextField jTF8;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
