/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.RandomStringUtils;

/**
 *
 * @author Sagnik Chakraborty
 */
public class AccountCreation_3 extends javax.swing.JFrame {

    /**
     * Creates new form AccountCreation_3
     */
    
    String CardNumber = "", CustomerID = "", ATMPin = "", Pwd = "", AccNo = "";
    String formNo = "", form = "";
    
    int flagR = 0, flagEQ = 0, flagI = 0;
    
    public AccountCreation_3(String frmno) {
        initComponents();
        
        formNo = frmno;
        
        setVisible(true);
        setResizable(false);
        form = "Form No.: "+formNo;
        jL10.setText(form);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Religion = new javax.swing.ButtonGroup();
        Category = new javax.swing.ButtonGroup();
        EdQf = new javax.swing.ButtonGroup();
        Identity = new javax.swing.ButtonGroup();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jL5 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jL6 = new javax.swing.JLabel();
        jRB1 = new javax.swing.JRadioButton();
        jRB2 = new javax.swing.JRadioButton();
        jRB3 = new javax.swing.JRadioButton();
        jRB4 = new javax.swing.JRadioButton();
        jRB5 = new javax.swing.JRadioButton();
        jTF2 = new javax.swing.JTextField();
        jL7 = new javax.swing.JLabel();
        jRB6 = new javax.swing.JRadioButton();
        jRB7 = new javax.swing.JRadioButton();
        jRB8 = new javax.swing.JRadioButton();
        jRB9 = new javax.swing.JRadioButton();
        jL8 = new javax.swing.JLabel();
        jRB10 = new javax.swing.JRadioButton();
        jRB11 = new javax.swing.JRadioButton();
        jRB12 = new javax.swing.JRadioButton();
        jRB13 = new javax.swing.JRadioButton();
        jRB14 = new javax.swing.JRadioButton();
        jRB15 = new javax.swing.JRadioButton();
        jRB16 = new javax.swing.JRadioButton();
        jTF3 = new javax.swing.JTextField();
        jL9 = new javax.swing.JLabel();
        jRB17 = new javax.swing.JRadioButton();
        jRB18 = new javax.swing.JRadioButton();
        jRB19 = new javax.swing.JRadioButton();
        jRB20 = new javax.swing.JRadioButton();
        jRB23 = new javax.swing.JRadioButton();
        jRB21 = new javax.swing.JRadioButton();
        jRB22 = new javax.swing.JRadioButton();
        jTF4 = new javax.swing.JTextField();
        jB1 = new javax.swing.JButton();
        jL10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL1.setText("ACCOUNT CREATION");

        jL2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jL2.setText("Page 3/3");

        jL3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jL3.setText("Additional Details:-");

        jL4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL4.setText("MONTHLY INCOME*:");

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL5.setText("Rs.");

        jTF1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL6.setText("RELIGION*:");

        Religion.add(jRB1);
        jRB1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB1.setText("HINDU");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB1, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB1, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB1MouseClicked(evt);
            }
        });

        Religion.add(jRB2);
        jRB2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB2.setText("MUSLIM");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB2, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB2, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB2MouseClicked(evt);
            }
        });

        Religion.add(jRB3);
        jRB3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB3.setText("CHRISTIAN");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB3, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB3, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB3MouseClicked(evt);
            }
        });

        Religion.add(jRB4);
        jRB4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB4.setText("SIKH");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB4, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB4, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB4MouseClicked(evt);
            }
        });

        Religion.add(jRB5);
        jRB5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB5.setText("OTHERS:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB5, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB5, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB5MouseClicked(evt);
            }
        });
        jRB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB5ActionPerformed(evt);
            }
        });

        jTF2.setEditable(false);
        jTF2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL7.setText("CATEGORY*:");

        Category.add(jRB6);
        jRB6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB6.setText("GENERAL");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB6, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB6, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB6MouseClicked(evt);
            }
        });

        Category.add(jRB7);
        jRB7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB7.setText("OBC");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB7, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB7, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB7MouseClicked(evt);
            }
        });

        Category.add(jRB8);
        jRB8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB8.setText("SC");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB8, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB8, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB8MouseClicked(evt);
            }
        });

        Category.add(jRB9);
        jRB9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB9.setText("ST");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB9, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB9, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB9MouseClicked(evt);
            }
        });

        jL8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL8.setText("EDUCATIONAL QUALIFICATION*:");

        EdQf.add(jRB10);
        jRB10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB10.setText("Below SSC");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB10, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB10, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB10MouseClicked(evt);
            }
        });

        EdQf.add(jRB11);
        jRB11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB11.setText("SSC");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB11, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB11, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB11MouseClicked(evt);
            }
        });

        EdQf.add(jRB12);
        jRB12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB12.setText("HSC");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB12, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB12, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB12MouseClicked(evt);
            }
        });

        EdQf.add(jRB13);
        jRB13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB13.setText("GRADUATE");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB13, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB13, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB13MouseClicked(evt);
            }
        });

        EdQf.add(jRB14);
        jRB14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB14.setText("POST GRADUATE");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB14, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB14, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB14MouseClicked(evt);
            }
        });

        EdQf.add(jRB15);
        jRB15.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB15.setText("PROFESSIONAL");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB15, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB15, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB15MouseClicked(evt);
            }
        });

        EdQf.add(jRB16);
        jRB16.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB16.setText("OTHERS:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB16, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB16, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB16MouseClicked(evt);
            }
        });
        jRB16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB16ActionPerformed(evt);
            }
        });

        jTF3.setEditable(false);
        jTF3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jL9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jL9.setText("PROOF OF IDENTITY*:");

        Identity.add(jRB17);
        jRB17.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB17.setText("PASSPORT");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB17, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB17, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB17MouseClicked(evt);
            }
        });

        Identity.add(jRB18);
        jRB18.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB18.setText("VOTER'S IDENTITY CARD");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB18, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB18, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB18MouseClicked(evt);
            }
        });

        Identity.add(jRB19);
        jRB19.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB19.setText("PAN CARD");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB19, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB19, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB19MouseClicked(evt);
            }
        });

        Identity.add(jRB20);
        jRB20.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB20.setText("DRIVING LICENCE");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB20, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB20, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB20MouseClicked(evt);
            }
        });

        Identity.add(jRB23);
        jRB23.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB23.setText("E-UID (AADHAAR CARD)");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB23, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB23, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB23MouseClicked(evt);
            }
        });

        Identity.add(jRB21);
        jRB21.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB21.setText("NREGA JOB CARD");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB21, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB21, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB21MouseClicked(evt);
            }
        });

        Identity.add(jRB22);
        jRB22.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRB22.setText("OTHERS(Any document notified by the Central Government/RBI):");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jRB22, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), jRB22, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        jRB22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRB22MouseClicked(evt);
            }
        });
        jRB22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB22ActionPerformed(evt);
            }
        });

        jTF4.setEditable(false);
        jTF4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jB1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB1.setText("SUBMIT");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jL10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRB4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jL6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB1)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRB6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRB7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRB8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRB9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL8)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB14)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB15))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB10)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB11)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB12)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB13))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jL9)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB23)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB21))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB17)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB18)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB19)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRB20))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRB22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL3)
                                    .addComponent(jL10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                                .addComponent(jL1)
                                .addGap(295, 295, 295)
                                .addComponent(jL2)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL1)
                            .addComponent(jL2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jL10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL4)
                    .addComponent(jL5)
                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL6)
                    .addComponent(jRB1)
                    .addComponent(jRB2)
                    .addComponent(jRB3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB4)
                    .addComponent(jRB5)
                    .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL7)
                    .addComponent(jRB6)
                    .addComponent(jRB7)
                    .addComponent(jRB8)
                    .addComponent(jRB9))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL8)
                    .addComponent(jRB10)
                    .addComponent(jRB11)
                    .addComponent(jRB12)
                    .addComponent(jRB13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB14)
                    .addComponent(jRB15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB16)
                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRB17)
                        .addComponent(jRB18)
                        .addComponent(jRB19)
                        .addComponent(jRB20))
                    .addComponent(jL9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB23)
                    .addComponent(jRB21))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB22)
                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jB1)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB5ActionPerformed
        flagR = 1;
    }//GEN-LAST:event_jRB5ActionPerformed

    private void jRB5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB5MouseClicked
        jTF2.setEditable(true);
    }//GEN-LAST:event_jRB5MouseClicked

    private void jRB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB1MouseClicked
        jTF2.setEditable(false);
    }//GEN-LAST:event_jRB1MouseClicked

    private void jRB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB2MouseClicked
        jTF2.setEditable(false);
    }//GEN-LAST:event_jRB2MouseClicked

    private void jRB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB3MouseClicked
        jTF2.setEditable(false);
    }//GEN-LAST:event_jRB3MouseClicked

    private void jRB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB4MouseClicked
        jTF2.setEditable(false);
    }//GEN-LAST:event_jRB4MouseClicked

    private void jRB6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB6MouseClicked

    private void jRB7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB7MouseClicked

    private void jRB8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB8MouseClicked

    private void jRB9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB9MouseClicked

    private void jRB10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB10MouseClicked
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB10MouseClicked

    private void jRB11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB11MouseClicked
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB11MouseClicked

    private void jRB12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB12MouseClicked
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB12MouseClicked

    private void jRB13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB13MouseClicked
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB13MouseClicked

    private void jRB14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB14MouseClicked
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB14MouseClicked

    private void jRB15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB15MouseClicked
        jTF3.setEditable(false);
    }//GEN-LAST:event_jRB15MouseClicked

    private void jRB16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB16MouseClicked
        jTF3.setEditable(true);
    }//GEN-LAST:event_jRB16MouseClicked

    private void jRB17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB17MouseClicked
        jTF4.setEditable(false);
    }//GEN-LAST:event_jRB17MouseClicked

    private void jRB18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB18MouseClicked
        jTF4.setEditable(false);
    }//GEN-LAST:event_jRB18MouseClicked

    private void jRB19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB19MouseClicked
        jTF4.setEditable(false);
    }//GEN-LAST:event_jRB19MouseClicked

    private void jRB20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB20MouseClicked
        jTF4.setEditable(false);
    }//GEN-LAST:event_jRB20MouseClicked

    private void jRB23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB23MouseClicked
        jTF4.setEditable(false);
    }//GEN-LAST:event_jRB23MouseClicked

    private void jRB21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB21MouseClicked
        jTF4.setEditable(false);
    }//GEN-LAST:event_jRB21MouseClicked

    private void jRB22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRB22MouseClicked
        jTF4.setEditable(true);
    }//GEN-LAST:event_jRB22MouseClicked

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
        
            CardNumber = RandomStringUtils.randomNumeric(16);
            AccNo = RandomStringUtils.randomNumeric(10);
            CustomerID = RandomStringUtils.randomAlphabetic(8);
            ATMPin = RandomStringUtils.randomNumeric(4);
            Pwd = RandomStringUtils.randomAlphanumeric(5);
        
            String Rel = "", cat = "", eduqua = "", idProf = "";
        
            if(flagR == 1)
                Rel = jTF2.getText();
            else
                Rel = Religion.getSelection().getActionCommand();
        
            cat = Category.getSelection().getActionCommand();
        
            if(flagEQ == 1)
                eduqua = jTF3.getText();
            else
                eduqua = EdQf.getSelection().getActionCommand();
        
            if(flagI == 1)
                idProf = jTF4.getText();
            else
                idProf = Identity.getSelection().getActionCommand();
        
            //String query = " insert into AccountInfo (MonthlyInc, Religion, Category, EduQual, IdenProof)" + " values (?, ?, ?, ?, ?)";
            String query = "update AccountInfo set MonthlyInc=?, Religion=?, Category=?, EduQual=?, IdenProof=? where FormNo = ?";
        
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,jTF1.getText());
            jTF1.setEditable(false);
            preparedStmt.setString(2,Rel);
            jRB1.setEnabled(false);
            jRB2.setEnabled(false);
            jRB3.setEnabled(false);
            jRB4.setEnabled(false);
            jRB5.setEnabled(false);
            jTF2.setEditable(false);
            preparedStmt.setString(3,cat);
            jRB6.setEnabled(false);
            jRB7.setEnabled(false);
            jRB8.setEnabled(false);
            jRB9.setEnabled(false);
            preparedStmt.setString(4,eduqua);
            jRB10.setEnabled(false);
            jRB11.setEnabled(false);
            jRB12.setEnabled(false);
            jRB13.setEnabled(false);
            jRB14.setEnabled(false);
            jRB15.setEnabled(false);
            jRB16.setEnabled(false);
            jTF3.setEditable(false);
            preparedStmt.setString(5,idProf);
            jRB17.setEnabled(false);
            jRB18.setEnabled(false);
            jRB19.setEnabled(false);
            jRB20.setEnabled(false);
            jRB21.setEnabled(false);
            jRB22.setEnabled(false);
            jRB23.setEnabled(false);
            jTF4.setEditable(false);
            preparedStmt.setString(6,formNo);
            
            preparedStmt.execute();
            
            while(true)
            {
                query = "select * from AccountInfo where AccNo=?";
                preparedStmt = conn.prepareStatement(query);
                preparedStmt.setString(1, AccNo);
            
                ResultSet rs = preparedStmt.executeQuery();  
                if(rs.next()) 
                {  
                    AccNo = RandomStringUtils.randomNumeric(10);
                }
                else
                {
                    break;
                }
            }
            
            while(true)
            {
                query = "select * from AccountInfo where CardNo=?";
                preparedStmt = conn.prepareStatement(query);
                preparedStmt.setString(1, CardNumber);
            
                ResultSet rs = preparedStmt.executeQuery();  
                if(rs.next()) 
                {  
                    CardNumber = RandomStringUtils.randomNumeric(16);
                }
                else
                {
                    break;
                }
            }
            
            //query = " insert into AccountInfo (CustId, CardNo, ATMPin, Pswd)" + " values (?, ?, ?, ?)";
            query = "update AccountInfo set CustId=?, CardNo=?, ATMPin=?, Pswd=?, AccNo=? where FormNo = ?";
        
            preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,CustomerID);
            preparedStmt.setString(2,CardNumber);
            preparedStmt.setString(3,ATMPin);
            preparedStmt.setString(4,Pwd);
            preparedStmt.setString(5,AccNo);
            preparedStmt.setString(6,formNo);
            
            preparedStmt.execute();
            
            JOptionPane.showMessageDialog(null, "Account No.: "+AccNo+"\nCustomer ID: "+CustomerID+"\nCard Number: "+CardNumber+"\nATM Pin: "+ATMPin+"\nPassword: "+Pwd);
            JOptionPane.showMessageDialog(null, "Account creation was Successfull!!");
            
            String balance = "BalanceInfo_"+AccNo;
            
            query = "create table "+balance+"(AccNo varchar(100), date_d_w varchar(50), Deposit varchar(100), Withdraw varchar(100), Balance varchar(200), Details varchar(500))";
        
            preparedStmt = conn.prepareStatement(query);
            preparedStmt.execute();
            
            java.time.LocalDate ldate = java.time.LocalDate.now();
            String date = ldate.toString();
            
            query = "insert into "+balance+" (AccNo, Date_d_w, Balance)" + " values (?, ?, ?)";
            
            String Bal = "0";
            
            preparedStmt = conn.prepareStatement(query);
            
            preparedStmt.setString(1,AccNo);
            preparedStmt.setString(2,date);
            preparedStmt.setString(3,Bal);
            
            preparedStmt.execute();
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
            
    }//GEN-LAST:event_jB1ActionPerformed

    private void jRB16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB16ActionPerformed
        flagEQ = 1;
    }//GEN-LAST:event_jRB16ActionPerformed

    private void jRB22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB22ActionPerformed
        flagI = 1;
    }//GEN-LAST:event_jRB22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountCreation_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountCreation_3("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Category;
    private javax.swing.ButtonGroup EdQf;
    private javax.swing.ButtonGroup Identity;
    private javax.swing.ButtonGroup Religion;
    private javax.swing.JButton jB1;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JRadioButton jRB1;
    private javax.swing.JRadioButton jRB10;
    private javax.swing.JRadioButton jRB11;
    private javax.swing.JRadioButton jRB12;
    private javax.swing.JRadioButton jRB13;
    private javax.swing.JRadioButton jRB14;
    private javax.swing.JRadioButton jRB15;
    private javax.swing.JRadioButton jRB16;
    private javax.swing.JRadioButton jRB17;
    private javax.swing.JRadioButton jRB18;
    private javax.swing.JRadioButton jRB19;
    private javax.swing.JRadioButton jRB2;
    private javax.swing.JRadioButton jRB20;
    private javax.swing.JRadioButton jRB21;
    private javax.swing.JRadioButton jRB22;
    private javax.swing.JRadioButton jRB23;
    private javax.swing.JRadioButton jRB3;
    private javax.swing.JRadioButton jRB4;
    private javax.swing.JRadioButton jRB5;
    private javax.swing.JRadioButton jRB6;
    private javax.swing.JRadioButton jRB7;
    private javax.swing.JRadioButton jRB8;
    private javax.swing.JRadioButton jRB9;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
