/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sagnik Chakraborty
 */
public class DetailsAlteration extends javax.swing.JFrame {

    /**
     * Creates new form DetailsAlteration
     */
    
    String name = "";
    String AccNo = "";
    String ToggleAcc = "";
    String bnName = "";
    String formNo = "";
    
    public DetailsAlteration(String nm, String acc, String bnm, String frmn) {
        initComponents();
        
        name = nm;
        AccNo = acc;
        bnName = bnm;
        formNo = frmn;
        
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, AccNo);
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                jTF7.setText(name);
                String acno = "000000-XXXXXX"+AccNo.substring(6);
                jTF2.setText(acno);
                ToggleAcc = acno;
                String cdno = rs.getString(4);
                String card = "XXXX XXXX XXXX "+cdno.substring(12);
                jTF10.setText(card);
                jTF6.setText(rs.getString(3));
                jTF1.setText(rs.getString(2));
                jTF3.setText("*****");
                jTF5.setText(rs.getString(1));
                jTF8.setText(rs.getString(8));
                jTF9.setText(rs.getString(9));
                jTF11.setText("XXXX");
                jTF12.setText(rs.getString(10));
                jTF13.setText(rs.getString(11));
                jTF14.setText(rs.getString(12));
                jTF15.setText(rs.getString(13));
                jTF16.setText(rs.getString(14));
                jTF17.setText(rs.getString(15));
                if(rs.getString(15) == "")
                    jTF17.setText("-");
                //else
                    //jTF16.setText(rs.getString(15));
                jTF18.setText(rs.getString(16));
                jTF19.setText(rs.getString(17));
                jTA1.setText(rs.getString(18));
                jTF20.setText(rs.getString(19));
                jTF21.setText(rs.getString(20));
                jTF22.setText(rs.getString(22));
                jTF23.setText(rs.getString(21));
                jTF24.setText(rs.getString(23));
                jTF25.setText(rs.getString(24));
                jTF26.setText(rs.getString(25));
                jTF27.setText(rs.getString(26));
                jTF28.setText(rs.getString(27));
                jTF29.setText(rs.getString(28));
            }
            
            String balance = "BalanceInfo_"+AccNo;
            
            query = "select * from "+balance+" order by date_d_w asc";
            
            preparedStmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE , ResultSet.CONCUR_UPDATABLE);
            
            rs = preparedStmt.executeQuery();
            
            if(rs.last() == true) 
            {  
                jTF4.setText(rs.getString(5)+".00");
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
        
        setVisible(true);
        //setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jTF2 = new javax.swing.JTextField();
        jTB1 = new javax.swing.JToggleButton();
        jL5 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jL6 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        jL7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jL8 = new javax.swing.JLabel();
        jTF5 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jL9 = new javax.swing.JLabel();
        jTF6 = new javax.swing.JTextField();
        jL10 = new javax.swing.JLabel();
        jTF7 = new javax.swing.JTextField();
        jL11 = new javax.swing.JLabel();
        jTF8 = new javax.swing.JTextField();
        jL12 = new javax.swing.JLabel();
        jTF9 = new javax.swing.JTextField();
        jL13 = new javax.swing.JLabel();
        jTF10 = new javax.swing.JTextField();
        jL14 = new javax.swing.JLabel();
        jTF11 = new javax.swing.JTextField();
        jL15 = new javax.swing.JLabel();
        jTF12 = new javax.swing.JTextField();
        jL16 = new javax.swing.JLabel();
        jTF13 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jL17 = new javax.swing.JLabel();
        jTF14 = new javax.swing.JTextField();
        jL18 = new javax.swing.JLabel();
        jTF15 = new javax.swing.JTextField();
        jL19 = new javax.swing.JLabel();
        jTF16 = new javax.swing.JTextField();
        jL20 = new javax.swing.JLabel();
        jTF17 = new javax.swing.JTextField();
        jTF18 = new javax.swing.JTextField();
        jL21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jL22 = new javax.swing.JLabel();
        jTF19 = new javax.swing.JTextField();
        jL23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA1 = new javax.swing.JTextArea();
        jL24 = new javax.swing.JLabel();
        jTF20 = new javax.swing.JTextField();
        jL25 = new javax.swing.JLabel();
        jTF21 = new javax.swing.JTextField();
        jL26 = new javax.swing.JLabel();
        jTF22 = new javax.swing.JTextField();
        jL27 = new javax.swing.JLabel();
        jTF23 = new javax.swing.JTextField();
        jL28 = new javax.swing.JLabel();
        jTF24 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jL29 = new javax.swing.JLabel();
        jTF25 = new javax.swing.JTextField();
        jL30 = new javax.swing.JLabel();
        jL31 = new javax.swing.JLabel();
        jTF26 = new javax.swing.JTextField();
        jL32 = new javax.swing.JLabel();
        jTF27 = new javax.swing.JTextField();
        jL33 = new javax.swing.JLabel();
        jTF28 = new javax.swing.JTextField();
        jL34 = new javax.swing.JLabel();
        jTF29 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        edit6 = new javax.swing.JButton();
        save6 = new javax.swing.JButton();
        edit7 = new javax.swing.JButton();
        save7 = new javax.swing.JButton();
        edit8 = new javax.swing.JButton();
        save8 = new javax.swing.JButton();
        edit9 = new javax.swing.JButton();
        save9 = new javax.swing.JButton();
        edit12 = new javax.swing.JButton();
        save12 = new javax.swing.JButton();
        edit13 = new javax.swing.JButton();
        save13 = new javax.swing.JButton();
        edit14 = new javax.swing.JButton();
        save14 = new javax.swing.JButton();
        edit15 = new javax.swing.JButton();
        save15 = new javax.swing.JButton();
        edit16 = new javax.swing.JButton();
        save16 = new javax.swing.JButton();
        edit17 = new javax.swing.JButton();
        save17 = new javax.swing.JButton();
        edit18 = new javax.swing.JButton();
        save18 = new javax.swing.JButton();
        edit19 = new javax.swing.JButton();
        save19 = new javax.swing.JButton();
        edit20 = new javax.swing.JButton();
        save20 = new javax.swing.JButton();
        edit21 = new javax.swing.JButton();
        save21 = new javax.swing.JButton();
        edit22 = new javax.swing.JButton();
        save22 = new javax.swing.JButton();
        edit23 = new javax.swing.JButton();
        save23 = new javax.swing.JButton();
        edit24 = new javax.swing.JButton();
        save24 = new javax.swing.JButton();
        edit25 = new javax.swing.JButton();
        save25 = new javax.swing.JButton();
        edit26 = new javax.swing.JButton();
        save26 = new javax.swing.JButton();
        edit27 = new javax.swing.JButton();
        save27 = new javax.swing.JButton();
        edit28 = new javax.swing.JButton();
        save28 = new javax.swing.JButton();
        edit29 = new javax.swing.JButton();
        save29 = new javax.swing.JButton();
        edit30 = new javax.swing.JButton();
        save30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jL1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL1.setText("SYNDICATE BANK");

        jL2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jL2.setText("Details Alteration:-");

        jL3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL3.setText("CUSTOMER ID:");

        jL4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL4.setText("ACCOUNT NUMBER:");

        jTF1.setEditable(false);
        jTF1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF2.setEditable(false);
        jTF2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTB1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jTB1.setText("UNHIDE");
        jTB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTB1ActionPerformed(evt);
            }
        });

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL5.setText("PASSWORD:");

        jTF3.setEditable(false);
        jTF3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL6.setText("BALANCE:");

        jTF4.setEditable(false);
        jTF4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL7.setText("Rs.");

        jL8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL8.setText("FORM NO.:");

        jTF5.setEditable(false);
        jTF5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL9.setText("BRANCH NAME:");

        jTF6.setEditable(false);
        jTF6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL10.setText("NAME:");

        jTF7.setEditable(false);
        jTF7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL11.setText("EMAIL:");

        jTF8.setEditable(false);
        jTF8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL12.setText("MOBILE NO.:");

        jTF9.setEditable(false);
        jTF9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL13.setText("CARD NO.:");

        jTF10.setEditable(false);
        jTF10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL14.setText("ATM PIN:");

        jTF11.setEditable(false);
        jTF11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL15.setText("D.O.B:");

        jTF12.setEditable(false);
        jTF12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL16.setText("GENDER:");

        jTF13.setEditable(false);
        jTF13.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL17.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL17.setText("MARITAL STATUS:");

        jTF14.setEditable(false);
        jTF14.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL18.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL18.setText("AADHAAR NO.:");

        jTF15.setEditable(false);
        jTF15.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL19.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL19.setText("FATHER NAME:");

        jTF16.setEditable(false);
        jTF16.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL20.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL20.setText("SPOUSE NAME:");

        jTF17.setEditable(false);
        jTF17.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jTF18.setEditable(false);
        jTF18.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL21.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL21.setText("MOTHER NAME:");

        jL22.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL22.setText("ADDRESS TYPE:");

        jTF19.setEditable(false);
        jTF19.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL23.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL23.setText("ADDRESS:");

        jTA1.setEditable(false);
        jTA1.setColumns(20);
        jTA1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTA1.setRows(5);
        jScrollPane1.setViewportView(jTA1);

        jL24.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL24.setText("CITY:");

        jTF20.setEditable(false);
        jTF20.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL25.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL25.setText("DISTRICT:");

        jTF21.setEditable(false);
        jTF21.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL26.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL26.setText("STATE:");

        jTF22.setEditable(false);
        jTF22.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL27.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL27.setText("PINCODE:");

        jTF23.setEditable(false);
        jTF23.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL28.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL28.setText("COUNTRY:");

        jTF24.setEditable(false);
        jTF24.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL29.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL29.setText("MONTHLY INCOME:");

        jTF25.setEditable(false);
        jTF25.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL30.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL30.setText("Rs.");

        jL31.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL31.setText("RELIGION:");

        jTF26.setEditable(false);
        jTF26.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL32.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL32.setText("CATEGORY:");

        jTF27.setEditable(false);
        jTF27.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL33.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL33.setText("EDUCATIONAL QUALIFICATION:");

        jTF28.setEditable(false);
        jTF28.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL34.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL34.setText("IDENTITY PROOF:");

        jTF29.setEditable(false);
        jTF29.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        update.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        edit6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit6.setText("EDIT");
        edit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit6ActionPerformed(evt);
            }
        });

        save6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save6.setText("SAVE");
        save6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save6ActionPerformed(evt);
            }
        });

        edit7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit7.setText("EDIT");
        edit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit7ActionPerformed(evt);
            }
        });

        save7.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save7.setText("SAVE");
        save7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save7ActionPerformed(evt);
            }
        });

        edit8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit8.setText("EDIT");
        edit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit8ActionPerformed(evt);
            }
        });

        save8.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save8.setText("SAVE");
        save8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save8ActionPerformed(evt);
            }
        });

        edit9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit9.setText("EDIT");
        edit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit9ActionPerformed(evt);
            }
        });

        save9.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save9.setText("SAVE");
        save9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save9ActionPerformed(evt);
            }
        });

        edit12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit12.setText("EDIT");
        edit12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit12ActionPerformed(evt);
            }
        });

        save12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save12.setText("SAVE");
        save12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save12ActionPerformed(evt);
            }
        });

        edit13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit13.setText("EDIT");
        edit13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit13ActionPerformed(evt);
            }
        });

        save13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save13.setText("SAVE");
        save13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save13ActionPerformed(evt);
            }
        });

        edit14.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit14.setText("EDIT");
        edit14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit14ActionPerformed(evt);
            }
        });

        save14.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save14.setText("SAVE");
        save14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save14ActionPerformed(evt);
            }
        });

        edit15.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit15.setText("EDIT");
        edit15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit15ActionPerformed(evt);
            }
        });

        save15.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save15.setText("SAVE");
        save15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save15ActionPerformed(evt);
            }
        });

        edit16.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit16.setText("EDIT");
        edit16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit16ActionPerformed(evt);
            }
        });

        save16.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save16.setText("SAVE");
        save16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save16ActionPerformed(evt);
            }
        });

        edit17.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit17.setText("EDIT");
        edit17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit17ActionPerformed(evt);
            }
        });

        save17.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save17.setText("SAVE");
        save17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save17ActionPerformed(evt);
            }
        });

        edit18.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit18.setText("EDIT");
        edit18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit18ActionPerformed(evt);
            }
        });

        save18.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save18.setText("SAVE");
        save18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save18ActionPerformed(evt);
            }
        });

        edit19.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit19.setText("EDIT");
        edit19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit19ActionPerformed(evt);
            }
        });

        save19.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save19.setText("SAVE");
        save19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save19ActionPerformed(evt);
            }
        });

        edit20.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit20.setText("EDIT");
        edit20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit20ActionPerformed(evt);
            }
        });

        save20.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save20.setText("SAVE");
        save20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save20ActionPerformed(evt);
            }
        });

        edit21.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit21.setText("EDIT");
        edit21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit21ActionPerformed(evt);
            }
        });

        save21.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save21.setText("SAVE");
        save21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save21ActionPerformed(evt);
            }
        });

        edit22.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit22.setText("EDIT");
        edit22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit22ActionPerformed(evt);
            }
        });

        save22.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save22.setText("SAVE");
        save22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save22ActionPerformed(evt);
            }
        });

        edit23.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit23.setText("EDIT");
        edit23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit23ActionPerformed(evt);
            }
        });

        save23.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save23.setText("SAVE");
        save23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save23ActionPerformed(evt);
            }
        });

        edit24.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit24.setText("EDIT");
        edit24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit24ActionPerformed(evt);
            }
        });

        save24.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save24.setText("SAVE");
        save24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save24ActionPerformed(evt);
            }
        });

        edit25.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit25.setText("EDIT");
        edit25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit25ActionPerformed(evt);
            }
        });

        save25.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save25.setText("SAVE");
        save25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save25ActionPerformed(evt);
            }
        });

        edit26.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit26.setText("EDIT");
        edit26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit26ActionPerformed(evt);
            }
        });

        save26.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save26.setText("SAVE");
        save26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save26ActionPerformed(evt);
            }
        });

        edit27.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit27.setText("EDIT");
        edit27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit27ActionPerformed(evt);
            }
        });

        save27.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save27.setText("SAVE");
        save27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save27ActionPerformed(evt);
            }
        });

        edit28.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit28.setText("EDIT");
        edit28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit28ActionPerformed(evt);
            }
        });

        save28.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save28.setText("SAVE");
        save28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save28ActionPerformed(evt);
            }
        });

        edit29.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit29.setText("EDIT");
        edit29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit29ActionPerformed(evt);
            }
        });

        save29.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save29.setText("SAVE");
        save29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save29ActionPerformed(evt);
            }
        });

        edit30.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        edit30.setText("EDIT");
        edit30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit30ActionPerformed(evt);
            }
        });

        save30.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        save30.setText("SAVE");
        save30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jL3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jL4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jL5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTB1))))
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(back)
                                .addGap(18, 18, 18)
                                .addComponent(update)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jL7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF8, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF10)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit7)
                                        .addGap(18, 18, 18)
                                        .addComponent(save7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit8)
                                        .addGap(18, 18, 18)
                                        .addComponent(save8))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit14)
                                        .addGap(18, 18, 18)
                                        .addComponent(save14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit15)
                                        .addGap(18, 18, 18)
                                        .addComponent(save15))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF18, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit18)
                                .addGap(18, 18, 18)
                                .addComponent(save18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit19)
                                .addGap(18, 18, 18)
                                .addComponent(save19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit20)
                                .addGap(18, 18, 18)
                                .addComponent(save20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit21)
                                .addGap(18, 18, 18)
                                .addComponent(save21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit23)
                                .addGap(18, 18, 18)
                                .addComponent(save23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit24)
                                .addGap(18, 18, 18)
                                .addComponent(save24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF24))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit22)
                                        .addGap(18, 18, 18)
                                        .addComponent(save22))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit25)
                                        .addGap(18, 18, 18)
                                        .addComponent(save25))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF25, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit26)
                                .addGap(18, 18, 18)
                                .addComponent(save26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF26, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit27)
                                .addGap(18, 18, 18)
                                .addComponent(save27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF27, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit28)
                                .addGap(18, 18, 18)
                                .addComponent(save28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF28, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit29)
                                .addGap(18, 18, 18)
                                .addComponent(save29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF29, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit30)
                                .addGap(18, 18, 18)
                                .addComponent(save30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit6)
                                .addGap(18, 18, 18)
                                .addComponent(save6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit9)
                                .addGap(18, 18, 18)
                                .addComponent(save9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jL16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF13)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit12)
                                        .addGap(18, 18, 18)
                                        .addComponent(save12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(edit13)
                                        .addGap(18, 18, 18)
                                        .addComponent(save13))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jL20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTF17, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edit17)
                                    .addGap(18, 18, 18)
                                    .addComponent(save17))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jL19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTF16, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(edit16)
                                    .addGap(18, 18, 18)
                                    .addComponent(save16))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL2)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL3)
                    .addComponent(jL4)
                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTB1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL5)
                            .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL6)
                    .addComponent(jL7)
                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL8)
                    .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL9)
                    .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit6)
                    .addComponent(save6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL10)
                    .addComponent(jTF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit7)
                    .addComponent(save7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL11)
                    .addComponent(jTF8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit8)
                    .addComponent(save8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL12)
                    .addComponent(jTF9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit9)
                    .addComponent(save9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL13)
                    .addComponent(jTF10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL14)
                    .addComponent(jTF11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL15)
                    .addComponent(jTF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit12)
                    .addComponent(save12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL16)
                    .addComponent(jTF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit13)
                    .addComponent(save13))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL17)
                    .addComponent(jTF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit14)
                    .addComponent(save14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL18)
                    .addComponent(jTF15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit15)
                    .addComponent(save15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL19)
                    .addComponent(jTF16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit16)
                    .addComponent(save16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL20)
                    .addComponent(jTF17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit17)
                    .addComponent(save17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL21)
                    .addComponent(jTF18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit18)
                    .addComponent(save18))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL22)
                    .addComponent(jTF19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit19)
                    .addComponent(save19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL23)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit20)
                        .addComponent(save20)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL24)
                    .addComponent(jTF20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit21)
                        .addComponent(save21)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL25)
                    .addComponent(jTF21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit22)
                        .addComponent(save22)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL26)
                    .addComponent(jTF22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit23)
                        .addComponent(save23)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL27)
                    .addComponent(jTF23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit24)
                        .addComponent(save24)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL28)
                    .addComponent(jTF24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit25)
                        .addComponent(save25)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL29)
                    .addComponent(jTF25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit26)
                        .addComponent(save26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL31)
                    .addComponent(jTF26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit27)
                        .addComponent(save27)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL32)
                    .addComponent(jTF27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit28)
                        .addComponent(save28)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL33)
                    .addComponent(jTF28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit29)
                        .addComponent(save29)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL34)
                    .addComponent(jTF29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edit30)
                        .addComponent(save30)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(back))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTB1ActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, AccNo);
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                
                String acno = "000000-XXXXXX"+AccNo.substring(6);
                if(jTB1.isSelected())
                {
                    jTF2.setText("000000-"+AccNo);
                    jTB1.setText("HIDE");
                    ToggleAcc = "000000-"+AccNo;
                }
                else
                {
                    jTF2.setText(acno);
                    jTB1.setText("UNHIDE");
                    ToggleAcc = acno;
                }
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_jTB1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new ProfileNet(name,AccNo,bnName,formNo);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void edit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit6ActionPerformed
        jTF6.setEditable(true);
    }//GEN-LAST:event_edit6ActionPerformed

    private void save6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save6ActionPerformed
        jTF6.setEditable(false);
    }//GEN-LAST:event_save6ActionPerformed

    private void edit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit7ActionPerformed
        jTF7.setEditable(true);
    }//GEN-LAST:event_edit7ActionPerformed

    private void edit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit8ActionPerformed
        jTF8.setEditable(true);
    }//GEN-LAST:event_edit8ActionPerformed

    private void edit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit9ActionPerformed
        jTF9.setEditable(true);
    }//GEN-LAST:event_edit9ActionPerformed

    private void edit12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit12ActionPerformed
        jTF12.setEditable(true);
    }//GEN-LAST:event_edit12ActionPerformed

    private void edit13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit13ActionPerformed
        jTF13.setEditable(true);
    }//GEN-LAST:event_edit13ActionPerformed

    private void edit14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit14ActionPerformed
        jTF14.setEditable(true);
    }//GEN-LAST:event_edit14ActionPerformed

    private void edit15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit15ActionPerformed
        jTF15.setEditable(true);
    }//GEN-LAST:event_edit15ActionPerformed

    private void edit16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit16ActionPerformed
        jTF16.setEditable(true);
    }//GEN-LAST:event_edit16ActionPerformed

    private void edit17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit17ActionPerformed
        jTF17.setEditable(true);
    }//GEN-LAST:event_edit17ActionPerformed

    private void edit18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit18ActionPerformed
        jTF18.setEditable(true);
    }//GEN-LAST:event_edit18ActionPerformed

    private void edit19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit19ActionPerformed
        jTF19.setEditable(true);
    }//GEN-LAST:event_edit19ActionPerformed

    private void edit20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit20ActionPerformed
        jTA1.setEditable(true);
    }//GEN-LAST:event_edit20ActionPerformed

    private void edit21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit21ActionPerformed
        jTF20.setEditable(true);
    }//GEN-LAST:event_edit21ActionPerformed

    private void edit22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit22ActionPerformed
        jTF21.setEditable(true);
    }//GEN-LAST:event_edit22ActionPerformed

    private void edit23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit23ActionPerformed
        jTF22.setEditable(true);
    }//GEN-LAST:event_edit23ActionPerformed

    private void edit24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit24ActionPerformed
        jTF23.setEditable(true);
    }//GEN-LAST:event_edit24ActionPerformed

    private void edit25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit25ActionPerformed
        jTF24.setEditable(true);
    }//GEN-LAST:event_edit25ActionPerformed

    private void edit26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit26ActionPerformed
        jTF25.setEditable(true);
    }//GEN-LAST:event_edit26ActionPerformed

    private void edit27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit27ActionPerformed
        jTF26.setEditable(true);
    }//GEN-LAST:event_edit27ActionPerformed

    private void edit28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit28ActionPerformed
        jTF27.setEditable(true);
    }//GEN-LAST:event_edit28ActionPerformed

    private void edit29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit29ActionPerformed
        jTF28.setEditable(true);
    }//GEN-LAST:event_edit29ActionPerformed

    private void edit30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit30ActionPerformed
        jTF29.setEditable(true);
    }//GEN-LAST:event_edit30ActionPerformed

    private void save7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save7ActionPerformed
        jTF7.setEditable(false);
    }//GEN-LAST:event_save7ActionPerformed

    private void save8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save8ActionPerformed
        jTF8.setEditable(false);
    }//GEN-LAST:event_save8ActionPerformed

    private void save9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save9ActionPerformed
        jTF9.setEditable(false);
    }//GEN-LAST:event_save9ActionPerformed

    private void save12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save12ActionPerformed
        jTF12.setEditable(false);
    }//GEN-LAST:event_save12ActionPerformed

    private void save13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save13ActionPerformed
        jTF13.setEditable(false);
    }//GEN-LAST:event_save13ActionPerformed

    private void save14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save14ActionPerformed
        jTF14.setEditable(false);
    }//GEN-LAST:event_save14ActionPerformed

    private void save15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save15ActionPerformed
        jTF15.setEditable(false);
    }//GEN-LAST:event_save15ActionPerformed

    private void save16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save16ActionPerformed
        jTF16.setEditable(false);
    }//GEN-LAST:event_save16ActionPerformed

    private void save17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save17ActionPerformed
        jTF17.setEditable(false);
    }//GEN-LAST:event_save17ActionPerformed

    private void save18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save18ActionPerformed
        jTF18.setEditable(false);
    }//GEN-LAST:event_save18ActionPerformed

    private void save19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save19ActionPerformed
        jTF19.setEditable(false);
    }//GEN-LAST:event_save19ActionPerformed

    private void save20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save20ActionPerformed
        jTA1.setEditable(false);
    }//GEN-LAST:event_save20ActionPerformed

    private void save21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save21ActionPerformed
        jTF20.setEditable(false);
    }//GEN-LAST:event_save21ActionPerformed

    private void save22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save22ActionPerformed
        jTF21.setEditable(false);
    }//GEN-LAST:event_save22ActionPerformed

    private void save23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save23ActionPerformed
        jTF22.setEditable(false);
    }//GEN-LAST:event_save23ActionPerformed

    private void save24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save24ActionPerformed
        jTF23.setEditable(false);
    }//GEN-LAST:event_save24ActionPerformed

    private void save25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save25ActionPerformed
        jTF24.setEditable(false);
    }//GEN-LAST:event_save25ActionPerformed

    private void save26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save26ActionPerformed
        jTF25.setEditable(false);
    }//GEN-LAST:event_save26ActionPerformed

    private void save27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save27ActionPerformed
        jTF26.setEditable(false);
    }//GEN-LAST:event_save27ActionPerformed

    private void save28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save28ActionPerformed
        jTF27.setEditable(false);
    }//GEN-LAST:event_save28ActionPerformed

    private void save29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save29ActionPerformed
        jTF28.setEditable(false);
    }//GEN-LAST:event_save29ActionPerformed

    private void save30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save30ActionPerformed
        jTF29.setEditable(false);
    }//GEN-LAST:event_save30ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = " update AccountInfo set BranchName=?, Name=?, Email=?, MobNo=?, Dob=?, Gender=?, MarStat=?, AadhNo=?, FathName=?, SpoName=?, MothName=? where AccNo = ?";
            
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,jTF6.getText());
            preparedStmt.setString(2,jTF7.getText());
            preparedStmt.setString(3,jTF8.getText());
            preparedStmt.setString(4,jTF9.getText());
            preparedStmt.setString(5,jTF12.getText());
            preparedStmt.setString(6,jTF13.getText());
            preparedStmt.setString(7,jTF14.getText());
            preparedStmt.setString(8,jTF15.getText());
            preparedStmt.setString(9,jTF16.getText());
            preparedStmt.setString(10,jTF17.getText());
            preparedStmt.setString(11,jTF18.getText());
            preparedStmt.setString(12,AccNo);
            
            preparedStmt.execute();
            
            query = "update AccountInfo set AddType=?, Address=?, City=?, District=?, State=?, PinCode=?, Country=? where AccNo = ?";
            
            preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,jTF19.getText());
            preparedStmt.setString(2,jTA1.getText());
            preparedStmt.setString(3,jTF20.getText());
            preparedStmt.setString(4,jTF21.getText());
            preparedStmt.setString(5,jTF22.getText());
            preparedStmt.setString(6,jTF23.getText());
            preparedStmt.setString(7,jTF24.getText());
            preparedStmt.setString(8,AccNo);
            
            preparedStmt.execute();
            
            query = "update AccountInfo set MonthlyInc=?, Religion=?, Category=?, EduQual=?, IdenProof=? where AccNo = ?";
        
            preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,jTF25.getText());
            preparedStmt.setString(2,jTF26.getText());
            preparedStmt.setString(3,jTF27.getText());
            preparedStmt.setString(4,jTF28.getText());
            preparedStmt.setString(5,jTF29.getText());
            preparedStmt.setString(6,AccNo);
            
            preparedStmt.execute();
            
            /*
            query = "update AccountInfo set CustId=?, CardNo=?, ATMPin=?, Pswd=?, AccNo=? where FormNo = ?";
        
            preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1,CustomerID);
            preparedStmt.setString(2,CardNumber);
            preparedStmt.setString(3,ATMPin);
            preparedStmt.setString(4,Pwd);
            preparedStmt.setString(5,AccNo);
            preparedStmt.setString(6,formNo);
            
            preparedStmt.execute();
            */
            
            JOptionPane.showMessageDialog(null, "Upadation was Successfull!!");
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsAlteration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsAlteration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsAlteration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsAlteration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsAlteration("","","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton edit12;
    private javax.swing.JButton edit13;
    private javax.swing.JButton edit14;
    private javax.swing.JButton edit15;
    private javax.swing.JButton edit16;
    private javax.swing.JButton edit17;
    private javax.swing.JButton edit18;
    private javax.swing.JButton edit19;
    private javax.swing.JButton edit20;
    private javax.swing.JButton edit21;
    private javax.swing.JButton edit22;
    private javax.swing.JButton edit23;
    private javax.swing.JButton edit24;
    private javax.swing.JButton edit25;
    private javax.swing.JButton edit26;
    private javax.swing.JButton edit27;
    private javax.swing.JButton edit28;
    private javax.swing.JButton edit29;
    private javax.swing.JButton edit30;
    private javax.swing.JButton edit6;
    private javax.swing.JButton edit7;
    private javax.swing.JButton edit8;
    private javax.swing.JButton edit9;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL12;
    private javax.swing.JLabel jL13;
    private javax.swing.JLabel jL14;
    private javax.swing.JLabel jL15;
    private javax.swing.JLabel jL16;
    private javax.swing.JLabel jL17;
    private javax.swing.JLabel jL18;
    private javax.swing.JLabel jL19;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL20;
    private javax.swing.JLabel jL21;
    private javax.swing.JLabel jL22;
    private javax.swing.JLabel jL23;
    private javax.swing.JLabel jL24;
    private javax.swing.JLabel jL25;
    private javax.swing.JLabel jL26;
    private javax.swing.JLabel jL27;
    private javax.swing.JLabel jL28;
    private javax.swing.JLabel jL29;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL30;
    private javax.swing.JLabel jL31;
    private javax.swing.JLabel jL32;
    private javax.swing.JLabel jL33;
    private javax.swing.JLabel jL34;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTA1;
    private javax.swing.JToggleButton jTB1;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF10;
    private javax.swing.JTextField jTF11;
    private javax.swing.JTextField jTF12;
    private javax.swing.JTextField jTF13;
    private javax.swing.JTextField jTF14;
    private javax.swing.JTextField jTF15;
    private javax.swing.JTextField jTF16;
    private javax.swing.JTextField jTF17;
    private javax.swing.JTextField jTF18;
    private javax.swing.JTextField jTF19;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF20;
    private javax.swing.JTextField jTF21;
    private javax.swing.JTextField jTF22;
    private javax.swing.JTextField jTF23;
    private javax.swing.JTextField jTF24;
    private javax.swing.JTextField jTF25;
    private javax.swing.JTextField jTF26;
    private javax.swing.JTextField jTF27;
    private javax.swing.JTextField jTF28;
    private javax.swing.JTextField jTF29;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JTextField jTF6;
    private javax.swing.JTextField jTF7;
    private javax.swing.JTextField jTF8;
    private javax.swing.JTextField jTF9;
    private javax.swing.JButton save12;
    private javax.swing.JButton save13;
    private javax.swing.JButton save14;
    private javax.swing.JButton save15;
    private javax.swing.JButton save16;
    private javax.swing.JButton save17;
    private javax.swing.JButton save18;
    private javax.swing.JButton save19;
    private javax.swing.JButton save20;
    private javax.swing.JButton save21;
    private javax.swing.JButton save22;
    private javax.swing.JButton save23;
    private javax.swing.JButton save24;
    private javax.swing.JButton save25;
    private javax.swing.JButton save26;
    private javax.swing.JButton save27;
    private javax.swing.JButton save28;
    private javax.swing.JButton save29;
    private javax.swing.JButton save30;
    private javax.swing.JButton save6;
    private javax.swing.JButton save7;
    private javax.swing.JButton save8;
    private javax.swing.JButton save9;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
