/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import javax.swing.JOptionPane;

/**
 *
 * @author Sagnik Chakraborty
 */
public class FirstPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    public FirstPage() {
        initComponents();
        
        setVisible(true);
        //setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jL5 = new javax.swing.JLabel();
        jL6 = new javax.swing.JLabel();
        jL7 = new javax.swing.JLabel();
        jL8 = new javax.swing.JLabel();
        jL9 = new javax.swing.JLabel();
        jL10 = new javax.swing.JLabel();
        jL11 = new javax.swing.JLabel();
        jL12 = new javax.swing.JLabel();
        jL13 = new javax.swing.JLabel();
        jL14 = new javax.swing.JLabel();
        jL15 = new javax.swing.JLabel();
        jL16 = new javax.swing.JLabel();
        jL17 = new javax.swing.JLabel();
        jL18 = new javax.swing.JLabel();
        jL19 = new javax.swing.JLabel();
        jL20 = new javax.swing.JLabel();
        jL21 = new javax.swing.JLabel();
        jL22 = new javax.swing.JLabel();
        jL23 = new javax.swing.JLabel();
        jL24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jL25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL1.setForeground(new java.awt.Color(255, 0, 0));
        jL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL1.setText("BANKING SECTOR PROJECT");

        jL2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL2.setText("DEVELOPER:");

        jL3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL3.setForeground(new java.awt.Color(0, 0, 255));
        jL3.setText("SAGNIK CHAKRABORTY");

        jL4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL4.setText("BANK NAME:");

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL5.setForeground(new java.awt.Color(0, 0, 255));
        jL5.setText("SYNDICATE BANK");

        jL6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL6.setText("START DATE:");

        jL7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL7.setForeground(new java.awt.Color(0, 0, 255));
        jL7.setText("01/01/2022");

        jL8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL8.setText("STATUS:");

        jL9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL9.setForeground(new java.awt.Color(0, 0, 255));
        jL9.setText("UNDER DEVELOPMENT");

        jL10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL10.setText("FRONT-END:");

        jL11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL11.setForeground(new java.awt.Color(0, 0, 255));
        jL11.setText("JAVA");

        jL12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL12.setText("BACK-END:");

        jL13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL13.setForeground(new java.awt.Color(0, 0, 255));
        jL13.setText("ORACLE");

        jL14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL14.setText("FILE SYSTEMS:");

        jL15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL15.setForeground(new java.awt.Color(0, 0, 255));
        jL15.setText("PDF, TEXT DOCUMENT");

        jL16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL16.setText("SYNOPSIS:");

        jL17.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL17.setForeground(new java.awt.Color(0, 0, 255));
        jL17.setText("The Syndicate Bank gives two choices. A user can");

        jL18.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL18.setForeground(new java.awt.Color(0, 0, 255));
        jL18.setText("either choose ATM or Net Banking.");

        jL19.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL19.setForeground(new java.awt.Color(0, 0, 255));
        jL19.setText("1. ATM gives the user the facilities of deposit, withdrawal,");

        jL20.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL20.setForeground(new java.awt.Color(0, 0, 255));
        jL20.setText("ministatement, pin change and account statement.");

        jL21.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL21.setForeground(new java.awt.Color(0, 0, 255));
        jL21.setText("2. Net Banking gives the user the facilities of fund transfer");

        jL22.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL22.setForeground(new java.awt.Color(0, 0, 255));
        jL22.setText("to another account of same bank, account information,");

        jL23.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL23.setForeground(new java.awt.Color(0, 0, 255));
        jL23.setText("account statement, account info alteration and");

        jL24.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL24.setForeground(new java.awt.Color(0, 0, 255));
        jL24.setText("login credentials alteration.");

        jButton1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jL25.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL25.setForeground(new java.awt.Color(0, 0, 255));
        jL25.setText("To experience the working of this project click on the button --> ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL18)
                                    .addComponent(jL17)
                                    .addComponent(jL19)
                                    .addComponent(jL21)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jL20))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jL23)
                                            .addComponent(jL22)
                                            .addComponent(jL24)))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jL25)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL2)
                    .addComponent(jL3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL4)
                    .addComponent(jL5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL6)
                    .addComponent(jL7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL8)
                    .addComponent(jL9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL10)
                    .addComponent(jL11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL12)
                    .addComponent(jL13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL14)
                    .addComponent(jL15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL16)
                    .addComponent(jL17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL18)
                .addGap(29, 29, 29)
                .addComponent(jL19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL20)
                .addGap(33, 33, 33)
                .addComponent(jL21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL24)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL25)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "ENJOY!!");
        dispose();
        new Start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPage();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL12;
    private javax.swing.JLabel jL13;
    private javax.swing.JLabel jL14;
    private javax.swing.JLabel jL15;
    private javax.swing.JLabel jL16;
    private javax.swing.JLabel jL17;
    private javax.swing.JLabel jL18;
    private javax.swing.JLabel jL19;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL20;
    private javax.swing.JLabel jL21;
    private javax.swing.JLabel jL22;
    private javax.swing.JLabel jL23;
    private javax.swing.JLabel jL24;
    private javax.swing.JLabel jL25;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
