/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sagnik Chakraborty
 */
public class MiniStatement extends javax.swing.JFrame {

    /**
     * Creates new form MiniStatement
     */
    
    String name = "";
    String AccNo = "";
    String bnName = "";
    String formNo = "";
    
    public MiniStatement(String nm, String acc, String bnm, String frmn) {
        initComponents();
        
        name = nm;
        AccNo = acc;
        bnName = bnm;
        formNo = frmn;
        
        java.time.LocalDate ldate = java.time.LocalDate.now();
                
        java.time.LocalTime ltime = java.time.LocalTime.now();
        String date = ldate.toString() +" "+ ltime.toString();
        
        jL3.setText(date);
        
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, AccNo);
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                jL10.setText(name);
                String acno = "000000-XXXXXX"+AccNo.substring(6);
                jL11.setText(acno);
                String cdno = rs.getString(4);
                String card = "XXXX XXXX XXXX "+cdno.substring(12);
                jL12.setText(card);
                jL13.setText(rs.getString(3));
            }
            
            String balance = "BalanceInfo_"+AccNo;
            
            query = "select * from "+balance+" order by date_d_w asc";
            
            preparedStmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE , ResultSet.CONCUR_UPDATABLE);
            
            rs = preparedStmt.executeQuery();
            
            if(rs.last() == true) 
            {  
                jL14.setText(rs.getString(5)+".00");
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
        
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jL4 = new javax.swing.JLabel();
        jL5 = new javax.swing.JLabel();
        jL6 = new javax.swing.JLabel();
        jL7 = new javax.swing.JLabel();
        jL8 = new javax.swing.JLabel();
        jL9 = new javax.swing.JLabel();
        jB2 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jL10 = new javax.swing.JLabel();
        jL11 = new javax.swing.JLabel();
        jL12 = new javax.swing.JLabel();
        jL13 = new javax.swing.JLabel();
        jL14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL1.setText("SYNDICATE BANK");

        jL2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jL2.setText("MINI STATEMENT");

        jL3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jL4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL4.setText("NAME:");

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL5.setText("ACCOUNT NUMBER:");

        jL6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL6.setText("CARD NUMBER:");

        jL7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL7.setText("BRANCH:");

        jL8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL8.setText("BALANCE:");

        jL9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL9.setText("Rs.");

        jB2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jB2.setText("BACK");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jB1.setText("SAVE");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jL10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL10.setForeground(new java.awt.Color(255, 51, 51));

        jL11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL11.setForeground(new java.awt.Color(255, 51, 51));

        jL12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL12.setForeground(new java.awt.Color(255, 51, 51));

        jL13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL13.setForeground(new java.awt.Color(255, 51, 51));

        jL14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jL14.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL12, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL13, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL14, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL10, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL11, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jB2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB1))
                            .addComponent(jL3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL1)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL1)
                .addGap(18, 18, 18)
                .addComponent(jL2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jL3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jL10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jL5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jL11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL6)
                    .addComponent(jL12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL7)
                    .addComponent(jL13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL8)
                    .addComponent(jL9)
                    .addComponent(jL14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1)
                    .addComponent(jB2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        new ProfileAtm(name,AccNo,bnName,formNo);
        dispose();
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        try
        {
            java.time.LocalDate ldate = java.time.LocalDate.now();
            java.time.LocalTime ltime = java.time.LocalTime.now();
            String date = ldate.toString() +"_"+ltime.toString().substring(0, 2)+"_"+ltime.toString().substring(3, 5)+"_"+ltime.toString().substring(6);
            //String fileName = "D:\\Banking_documents\\MiniStatements\\MiniStatement_"+date+".txt";
            //Path path = Paths.get(fileName);
            //Path p= Files.createFile(path);
            //FileOutputStream fos=new FileOutputStream(fileName, true);
            
            String path = "D:\\Banking_documents\\MiniStatements";
            
            File theDir = new File(path);
            
            if (!theDir.exists())
            {
                theDir.mkdirs();
            }
            
            String fn = path+"\\MiniStatement_"+date+".pdf";
            
            Document document = new Document();
            
            PdfWriter.getInstance(document, new FileOutputStream(fn));
            
            //document.open();
            
            //Paragraph para = new Paragraph();
            
            //document.close();
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, AccNo);
            
            String acno = "", cdno = "", card = "", brnch = "", Bal = "";
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                //jL10.setText(name);
                acno = "000000-XXXXXX"+AccNo.substring(6);
                //jL11.setText(acno);
                cdno = rs.getString(4);
                card = "XXXX XXXX XXXX "+cdno.substring(12);
                //jL12.setText(card);
                brnch = rs.getString(3);
            }
            
            String balance = "BalanceInfo_"+AccNo;
            
            query = "select * from "+balance+" order by date_d_w asc";
            
            preparedStmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE , ResultSet.CONCUR_UPDATABLE);
            
            rs = preparedStmt.executeQuery();
            
            if(rs.last() == true) 
            {  
                Bal = rs.getString(5)+".00";
            }
            
            String str = "";
            
            str = "\t\tSYNDICATE BANK\n\n"+"MINI STATEMENT\n\n"+"NAME:  "+name+"\nACCOUNT NUMBER:  "+acno+"\nCARD NUMBER:  "+card+"\nBRANCH:  "+brnch;
            str += "\n\nBALANCE:  Rs."+Bal;
            
            document.open();
            
            Paragraph para = new Paragraph(str);
            
            document.add(para);
            
            document.close();
            
            //byte[] b= str.getBytes();
            //fos.write(b);
            //fos.close();
            
            JOptionPane.showMessageDialog(null, "MiniStatement Successfully Saved!!");
        }
        catch(Exception e)  
        {  
            e.printStackTrace();          
        }
    }//GEN-LAST:event_jB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniStatement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniStatement("","","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL12;
    private javax.swing.JLabel jL13;
    private javax.swing.JLabel jL14;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    // End of variables declaration//GEN-END:variables
}
