/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sagnik Chakraborty
 */
public class PinChange extends javax.swing.JFrame {

    /**
     * Creates new form PinChange
     */
    
    String name = "";
    String AccNo = "";
    String bnName = "";
    String formNo = "";
    
    public PinChange(String nm, String acc, String bnm, String frmn) {
        initComponents();
        
        name = nm;
        AccNo = acc;
        bnName = bnm;
        formNo = frmn;
        
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jB1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jL4 = new javax.swing.JLabel();
        jL5 = new javax.swing.JLabel();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jPF1 = new javax.swing.JPasswordField();
        jPF2 = new javax.swing.JPasswordField();
        jPF3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL1.setText("SYNDICATE BANK");

        jL2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jL2.setText("Pin Change:-");

        jL3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL3.setText("PIN:");

        jB1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB1.setText("VALIDATE");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        jB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jB1KeyPressed(evt);
            }
        });

        jL4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL4.setText("NEW PIN:");

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL5.setText("CONFIRM PIN:");

        jB2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB2.setText("SAVE");
        jB2.setEnabled(false);
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB3.setText("BACK");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jPF1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jPF2.setEditable(false);
        jPF2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jPF3.setEditable(false);
        jPF3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB1)
                        .addGap(94, 94, 94))))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL5)
                    .addComponent(jL4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPF2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPF3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB3)
                .addGap(18, 18, 18)
                .addComponent(jB2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jL1))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL1)
                .addGap(18, 18, 18)
                .addComponent(jL2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL3)
                    .addComponent(jPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jB1)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL4)
                    .addComponent(jPF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL5)
                    .addComponent(jPF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB2)
                    .addComponent(jB3))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String tp = new String(jPF1.getPassword());
            
            String query = "select * from AccountInfo where ATMPin=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, tp);
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                jPF1.setEditable(false);
                jPF2.setEditable(true);
                jPF3.setEditable(true);
                jB2.setEnabled(true);
                jB1.setEnabled(false);
            } else {  
                JOptionPane.showMessageDialog(null, "ATM Pin didnot match!!");
                jPF1.setText("");
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        new ProfileAtm(name,AccNo,bnName,formNo);
        dispose();
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        try
        {
            String tp1 = new String(jPF2.getPassword());
            String tp2 = new String(jPF3.getPassword());
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            if(tp1.equals(tp2))
            {
                String query = "update AccountInfo set ATMPin=? where AccNo = ?";
                PreparedStatement preparedStmt = conn.prepareStatement(query);
                preparedStmt.setString(1, tp1);
                preparedStmt.setString(2, AccNo);
                
                preparedStmt.execute();
                
                jPF2.setEditable(false);
                jPF3.setEditable(false);
                
                JOptionPane.showMessageDialog(null, "Pin Changed Succesfully!!");
                
                new ProfileAtm(name,AccNo,bnName,formNo);
                dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "New and Confirmed Password didnot match!!");
                jPF2.setText("");
                jPF3.setText("");
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jB1KeyPressed
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            String tp = new String(jPF1.getPassword());
            
            String query = "select * from AccountInfo where ATMPin=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, tp);
            
            ResultSet rs = preparedStmt.executeQuery();  
            if (rs.next()) {  
                jPF1.setEditable(false);
                jPF2.setEditable(true);
                jPF3.setEditable(true);
                jB2.setEnabled(true);
                jB1.setEnabled(false);
            } else {  
                JOptionPane.showMessageDialog(null, "ATM Pin didnot match!!");
                jPF1.setText("");
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_jB1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PinChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PinChange("","","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JPasswordField jPF1;
    private javax.swing.JPasswordField jPF2;
    private javax.swing.JPasswordField jPF3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
