/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_sector;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.RandomStringUtils;

/**
 *
 * @author Sagnik Chakraborty
 */
public class SendFunds extends javax.swing.JFrame {

    /**
     * Creates new form SendFunds
     */
    
    String name = "";
    String AccNo = "";
    String bnName = "";
    String formNo = "";
    
    public SendFunds(String nm, String acc, String bnm, String frmn) {
        initComponents();
        
        name = nm;
        AccNo = acc;
        bnName = bnm;
        formNo = frmn;
        
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL1 = new javax.swing.JLabel();
        jL2 = new javax.swing.JLabel();
        jL3 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jL5 = new javax.swing.JLabel();
        jL6 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL1.setText("SYNDICATE BANK");

        jL2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jL2.setText("Fund Transfer:-");

        jL3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL3.setText("ACCOUNT NUMBER of RECIPIENT:");

        jTF1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jL5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL5.setText("AMOUNT to be TRANSFERED:");

        jL6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jL6.setText("Rs.");

        jTF3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        jB1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB1.setText("SEND");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jB2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jB2.setText("BACK");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jL5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jL2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jL3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jB2)
                        .addGap(18, 18, 18)
                        .addComponent(jB1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL1)
                .addGap(18, 18, 18)
                .addComponent(jL2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL3)
                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL5)
                    .addComponent(jL6)
                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1)
                    .addComponent(jB2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        new ProfileNet(name,AccNo,bnName,formNo);
        dispose();
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        try
        {
            String TrxnId = RandomStringUtils.randomNumeric(8);
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "hr", "hr");
            
            int amt = 0, balOwn=0, bal=0;
            String Amount = "";
            amt = Integer.parseInt(jTF3.getText());
            
            String query = "select * from AccountInfo where AccNo=?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, jTF1.getText());
            
            ResultSet rs = preparedStmt.executeQuery();  
            if ((rs.next()) && !(AccNo.equals(jTF1.getText()))) {  
                jTF1.setEditable(false);
                jTF3.setEditable(false);
            }
            else if(AccNo.equals(jTF1.getText()))
            {
                JOptionPane.showMessageDialog(null, "Cannot transfer to the same Account!!");
                jTF1.setText("");
            }
            else 
            {  
                JOptionPane.showMessageDialog(null, "Invalid Account Number!!");
                jTF1.setText("");
            }
            String w = jTF1.getText();
            String balanceOwn = "BalanceInfo_"+AccNo;
            String balance = "BalanceInfo_"+w;
            
            String BalOwn = "";
            String Bal = "";
            
            query = "select * from "+balanceOwn+" order by date_d_w asc";
            
            preparedStmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE , ResultSet.CONCUR_UPDATABLE);
            
            rs = preparedStmt.executeQuery();
            
            if(rs.last() == true) 
            {  
                BalOwn = rs.getString(5);
            }
            
            query = "select * from "+balance+" order by date_d_w asc";
            
            preparedStmt = conn.prepareStatement(query, ResultSet.TYPE_SCROLL_SENSITIVE , ResultSet.CONCUR_UPDATABLE);
            
            rs = preparedStmt.executeQuery();
            
            if(rs.last() == true) 
            {  
                Bal = rs.getString(5);
            } 
            
            balOwn = Integer.parseInt(BalOwn);
            bal = Integer.parseInt(Bal);
            if(amt > 50000)
                JOptionPane.showMessageDialog(null, "Cannot Transfer more than Rs. 50000 in one transaction!!");
            else
            {
                if(balOwn < amt)
                {
                    JOptionPane.showMessageDialog(null, "Insuficient Balance!!");
                }
                else
                {
                    bal += amt;
                    balOwn -= amt;
                    Bal = Integer.toString(bal);
                    BalOwn = Integer.toString(balOwn);
                    Amount = Integer.toString(amt);
                    
                    java.time.LocalDate ldate = java.time.LocalDate.now();
                    
                    java.time.LocalTime ltime = java.time.LocalTime.now();
                    String date = ldate.toString() +" "+ ltime.toString();
                    
                    query = "insert into "+balanceOwn+" (AccNo, date_d_w, Deposit, Withdraw, Balance, Details)" + " values (?, ?, ?, ?, ?, ?)";
                    
                    preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString(1, AccNo);
                    preparedStmt.setString(2, date);
                    preparedStmt.setString(3, "-");
                    preparedStmt.setString(4, Amount);
                    preparedStmt.setString(5, BalOwn);
                    preparedStmt.setString(6, "Trxn ID: "+TrxnId+"  Transfer of Funds to Account Number: "+jTF1.getText());
                    
                    preparedStmt.execute();
                    
                    query = "insert into "+balance+" (AccNo, date_d_w, Deposit, Withdraw, Balance, Details)" + " values (?, ?, ?, ?, ?, ?)";
                    
                    preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString(1, jTF1.getText());
                    preparedStmt.setString(2, date);
                    preparedStmt.setString(3, Amount);
                    preparedStmt.setString(4, "-");
                    preparedStmt.setString(5, Bal);
                    preparedStmt.setString(6, "Trxn ID: "+TrxnId+"  Transfer of Funds from Account Number: "+AccNo);
                    
                    preparedStmt.execute();
                    
                    JOptionPane.showMessageDialog(null, "Fund transfered to Account Number: "+jTF1.getText()+"!!");
                    
                    new ProfileNet(name,AccNo,bnName,formNo);
                    dispose();
                }
            }
        }
        catch (Exception ea)
        {
            System.err.println("Got an exception!");
            System.err.println(ea.getMessage());
        }
    }//GEN-LAST:event_jB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendFunds("","","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF3;
    // End of variables declaration//GEN-END:variables
}
